services:
    grafana-lgtm:
        image: 'grafana/otel-lgtm:latest'
        ports:
            - '3000:3000' # UI
            - '4317:4317'
            - '4318:4318'
    otel-collector:
        image: 'otel/opentelemetry-collector-contrib:latest'
        volumes:
            - './otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro'
            #- './otel-collector-output:/output:rw'
        ports:
            - '4318:4318'